/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package graphpresentation.statistic;

import graphpresentation.statistic.enums.PetriStatisticFunction;

import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.List;

/**
 *
 * @author kachm
 */
public class SelectFunctionDialog extends javax.swing.JDialog {
    private PetriStatisticFunction selectedFunction;

    /**
     * Creates new form SelectFunctionDialog
     */
    public SelectFunctionDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        selectFunctionPanel = new javax.swing.JPanel();
        functionListPanel = new javax.swing.JScrollPane();
        functionList = new javax.swing.JList<>();
        functionInfoPanel = new javax.swing.JPanel();
        functionTitle = new javax.swing.JLabel();
        functionDescription = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 0));
        selectFunctionBtn = new javax.swing.JButton();
        cancelSelectionBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Function insertion");
        setPreferredSize(new java.awt.Dimension(350, 300));

        selectFunctionPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Select function"));
        selectFunctionPanel.setPreferredSize(new java.awt.Dimension(200, 200));
        selectFunctionPanel.setLayout(new java.awt.BorderLayout());

        functionList.setModel(new javax.swing.AbstractListModel<String>() {
            List<String> functions = PetriStatisticFunction.getFunctionNames();
            public int getSize() { return functions.size(); }
            public String getElementAt(int i) { return functions.get(i); }
        });
        functionList.addListSelectionListener(e -> {
            this.selectedFunction = PetriStatisticFunction.getFunctionByIndex(functionList.getSelectedIndex());
            functionTitle.setText(selectedFunction.getTitle());
            functionDescription.setText(selectedFunction.getDescription());
        });
        functionList.setSelectedIndex(0);
        functionListPanel.setViewportView(functionList);

        selectFunctionPanel.add(functionListPanel, java.awt.BorderLayout.CENTER);

        functionInfoPanel.setPreferredSize(new java.awt.Dimension(357, 50));
        functionInfoPanel.setLayout(new java.awt.GridLayout(2, 0));

        functionTitle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        functionTitle.setPreferredSize(new java.awt.Dimension(39, 5));
        functionInfoPanel.add(functionTitle);

        functionDescription.setPreferredSize(new java.awt.Dimension(37, 25));
        functionInfoPanel.add(functionDescription);

        selectFunctionPanel.add(functionInfoPanel, java.awt.BorderLayout.PAGE_END);

        getContentPane().add(selectFunctionPanel, java.awt.BorderLayout.PAGE_START);

        jPanel1.add(filler1);

        selectFunctionBtn.setText("OK");
        selectFunctionBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        selectFunctionBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        selectFunctionBtn.addActionListener(e -> dispose());
        jPanel1.add(selectFunctionBtn);

        cancelSelectionBtn.setText("Cancel");
        cancelSelectionBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        cancelSelectionBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        cancelSelectionBtn.addActionListener(this::cancelSelectionBtnActionPerformed);
        jPanel1.add(cancelSelectionBtn);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                selectedFunction = null;
            }
        });
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelSelectionBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelSelectionBtnActionPerformed
        selectedFunction = null;
        dispose();
    }//GEN-LAST:event_cancelSelectionBtnActionPerformed

    private void okBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtnActionPerformed
        dispose();
    }//GEN-LAST:event_okBtnActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelSelectionBtn;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel functionDescription;
    private javax.swing.JPanel functionInfoPanel;
    private javax.swing.JList<String> functionList;
    private javax.swing.JScrollPane functionListPanel;
    private javax.swing.JLabel functionTitle;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton selectFunctionBtn;
    private javax.swing.JPanel selectFunctionPanel;
    // End of variables declaration//GEN-END:variables


    public PetriStatisticFunction getSelectedFunction() {
        return selectedFunction;
    }
}
