/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package graphpresentation.statistic;

import graphpresentation.statistic.enums.FunctionType;

import javax.swing.*;
import java.awt.*;
import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import java.util.List;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

/**
 * @author Andrii Kachmar
 */
public class StatisticMonitorDialog extends javax.swing.JDialog {
    /**
     * Creates new form StatisticMonitorDialog
     */
    public StatisticMonitorDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.parent = parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        contentLayout = new javax.swing.JSplitPane();
        formulaBarPanel = new javax.swing.JPanel();
        formulaActionsGroup = new javax.swing.JPanel();
        clearFormulaBtn = new javax.swing.JButton();
        formulaInfoBtn = new javax.swing.JButton();
        formulaPanel = new javax.swing.JScrollPane();
        formulaInputField = new javax.swing.JTextArea();
        mainContentPanel = new javax.swing.JPanel();
        contentTabs = new javax.swing.JTabbedPane();
        chartViewPanel = new javax.swing.JPanel();
        tableViewPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Statistic monitor");
        setPreferredSize(new java.awt.Dimension(845, 600));

        contentLayout.setDividerLocation(50);
        contentLayout.setDividerSize(3);
        contentLayout.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        contentLayout.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        contentLayout.setMinimumSize(new java.awt.Dimension(80, 40));
        contentLayout.setPreferredSize(new java.awt.Dimension(845, 40));

        formulaBarPanel.setPreferredSize(new java.awt.Dimension(314, 70));
        formulaBarPanel.setLayout(new java.awt.BorderLayout());

        formulaActionsGroup.setLayout(new java.awt.GridBagLayout());

        clearFormulaBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/close_icon.png"))); // NOI18N
        clearFormulaBtn.setContentAreaFilled(false);
        clearFormulaBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        clearFormulaBtn.setPreferredSize(new java.awt.Dimension(40, 40));
        clearFormulaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearFormulaBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        formulaActionsGroup.add(clearFormulaBtn, gridBagConstraints);

        formulaInfoBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utils/fx_icon.png"))); // NOI18N
        formulaInfoBtn.setContentAreaFilled(false);
        formulaInfoBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        formulaInfoBtn.setPreferredSize(new java.awt.Dimension(40, 40));
        formulaInfoBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                formulaInfoBtnActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTH;
        formulaActionsGroup.add(formulaInfoBtn, gridBagConstraints);

        formulaBarPanel.add(formulaActionsGroup, java.awt.BorderLayout.LINE_START);

        formulaPanel.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        formulaPanel.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);
        formulaPanel.setPreferredSize(new java.awt.Dimension(234, 60));

        formulaInputField.setColumns(20);
        formulaInputField.setLineWrap(true);
        formulaInputField.setRows(5);
        formulaInputField.setText("Enter your formula...");
        formulaInputField.setToolTipText("Enter your formula...");
        formulaInputField.setPreferredSize(new java.awt.Dimension(232, 60));
        formulaInputField.addKeyListener(new KeyAdapter() {
            @Override
            public void keyReleased(KeyEvent e) {
                onFormulaFieldKeyEventPerformed(e);
            }
        });
        formulaPanel.setViewportView(formulaInputField);
        formulaSuggestionPopup = new JPopupMenu();

        formulaBarPanel.add(formulaPanel, java.awt.BorderLayout.CENTER);

        contentLayout.setTopComponent(formulaBarPanel);

        mainContentPanel.setLayout(new javax.swing.BoxLayout(mainContentPanel, javax.swing.BoxLayout.LINE_AXIS));

        javax.swing.GroupLayout chartViewPanelLayout = new javax.swing.GroupLayout(chartViewPanel);
        chartViewPanel.setLayout(chartViewPanelLayout);
        chartViewPanelLayout.setHorizontalGroup(
                chartViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 845, Short.MAX_VALUE)
        );
        chartViewPanelLayout.setVerticalGroup(
                chartViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 470, Short.MAX_VALUE)
        );

        contentTabs.addTab("Chart view", chartViewPanel);

        javax.swing.GroupLayout tableViewPanelLayout = new javax.swing.GroupLayout(tableViewPanel);
        tableViewPanel.setLayout(tableViewPanelLayout);
        tableViewPanelLayout.setHorizontalGroup(
                tableViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 845, Short.MAX_VALUE)
        );
        tableViewPanelLayout.setVerticalGroup(
                tableViewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 470, Short.MAX_VALUE)
        );

        contentTabs.addTab("Table view", tableViewPanel);

        mainContentPanel.add(contentTabs);

        contentLayout.setRightComponent(mainContentPanel);

        getContentPane().add(contentLayout, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formulaInfoBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_formulaInfoBtnActionPerformed
        SelectFunctionDialog selectFunctionDialog = new SelectFunctionDialog(this.parent, true);
        selectFunctionDialog.setVisible(true);
        FunctionType selectedFunction = selectFunctionDialog.getSelectedFunction();
        if (selectedFunction != null) {
            String formula = selectedFunction.getFunctionName();
            formulaInputField.setText(formula); //TODO BUILD FORMULA HERE
        }
    }//GEN-LAST:event_formulaInfoBtnActionPerformed

    private void clearFormulaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearFormulaBtnActionPerformed
        formulaInputField.setText("");
    }//GEN-LAST:event_clearFormulaBtnActionPerformed

    private void onFormulaFieldKeyEventPerformed(KeyEvent e) {
        if (formulaInputField.getText().trim().isEmpty()) {
            return;
        }
        char keyChar = e.getKeyChar();
        if (Character.isLetterOrDigit(keyChar) || keyChar == KeyEvent.VK_BACK_SPACE) {
            showFormulaSuggestions();
        } else if (e.getKeyCode() == KeyEvent.VK_DOWN && formulaSuggestionPopup.isVisible()) {
            formulaSuggestionPopup.requestFocusInWindow();
        } else if (e.getKeyCode() == KeyEvent.VK_ENTER && formulaSuggestionPopup.isVisible()) {
            System.out.println(formulaSuggestionPopup.getComponent());
            formulaSuggestionPopup.setVisible(false);
        }
    }

    private void showFormulaSuggestions() {
        String input = formulaInputField.getText().trim();
        formulaSuggestionPopup.setVisible(false);
        Pattern pattern = Pattern.compile(".*[+\\-*/(]([^+\\-*/()]*)$");
        Matcher matcher = pattern.matcher(input);
        String formulaPrefix = matcher.find() ? matcher.group(1) : input;
        List<String> filteredSuggestions = FunctionType.getFunctionNames().stream()
                .filter(s -> s.toLowerCase().startsWith(formulaPrefix.toLowerCase()))
                .collect(Collectors.toList());
        if (!filteredSuggestions.isEmpty()) {
            formulaSuggestionPopup.removeAll();
            for (String suggestion : filteredSuggestions) {
                JMenuItem item = new JMenuItem(suggestion);
                item.addActionListener(e -> {
                    formulaInputField.setText(suggestion); //TODO BUILD FORMULA HERE
                    formulaSuggestionPopup.setVisible(false);
                });
                formulaSuggestionPopup.add(item);
            }
            Point position = formulaInputField.getCaret().getMagicCaretPosition();
            if (position != null) {
                formulaSuggestionPopup.show(formulaInputField, position.x, position.y + formulaInputField.getFontMetrics(formulaInputField.getFont()).getHeight());
            } else {
                formulaSuggestionPopup.show(formulaInputField, 0, formulaInputField.getHeight());
            }
            formulaInputField.requestFocus();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Frame parent;
    private javax.swing.JPanel chartViewPanel;
    private javax.swing.JButton clearFormulaBtn;
    private javax.swing.JSplitPane contentLayout;
    private javax.swing.JTabbedPane contentTabs;
    private javax.swing.JPanel formulaActionsGroup;
    private javax.swing.JPanel formulaBarPanel;
    private javax.swing.JButton formulaInfoBtn;
    private javax.swing.JTextArea formulaInputField;
    private javax.swing.JScrollPane formulaPanel;
    private javax.swing.JPanel mainContentPanel;
    private javax.swing.JPanel tableViewPanel;
    private javax.swing.JPopupMenu formulaSuggestionPopup;
    // End of variables declaration//GEN-END:variables
}
