server:
  port: 8080

spring:
  application:
    name: petri-server

springdoc:
  swagger-ui:
    path: /docs
  api-docs:
    path: /openapi.json

management:
  endpoints:
    web:
      exposure:
        include: health
      base-path: /
  endpoint:
    health:
      show-details: always

logging:
  level:
    ua.stetsenkoinna: INFO
