package ua.stetsenkoinna.graphpresentation;

import ua.stetsenkoinna.PetriObj.*;
import ua.stetsenkoinna.graphnet.*;
import ua.stetsenkoinna.utils.SafeParsingUtils;

import javax.swing.*;

/**
 *
 * @author Оля
 */
public class SetArc extends javax.swing.JFrame {

    private final PetriNetsPanel panel;

    private GraphArc chosenTie;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JRadioButton isInfRadioButton;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel quantityLabel;
    private javax.swing.JLabel quantityLabel1;
    private javax.swing.JTextField quantityTextField;
    private javax.swing.JTextField infParamNameField;
    private javax.swing.JPanel setTiePanel;
    // End of variables declaration//GEN-END:variables

    /**
     * Creates new form SetTie
     */
    public SetArc(PetriNetsPanel panel) {
        initComponents();
        this.setLocationRelativeTo(null);
        this.panel = panel;

        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);//<-- destroy only this frame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setTiePanel = new javax.swing.JPanel();
        quantityLabel = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        quantityTextField = new javax.swing.JTextField();
        isInfRadioButton = new javax.swing.JRadioButton();
        jTextField2 = new javax.swing.JTextField();
        quantityLabel1 = new javax.swing.JLabel();
        infParamNameField = new javax.swing.JTextField();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Link parameters");

        setTiePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Basic parameters"));

        quantityLabel.setText("Number of links");

        jRadioButton1.setText("Use the formula");
        jRadioButton1.setEnabled(false);

        isInfRadioButton.setText("Information link");

        jTextField2.setEnabled(false);

        quantityLabel1.setText("Information link (parameter name)");

        infParamNameField.setName(""); // NOI18N
        infParamNameField.addActionListener(this::infParamNameFieldActionPerformed);

        javax.swing.GroupLayout setTiePanelLayout = new javax.swing.GroupLayout(setTiePanel);
        setTiePanel.setLayout(setTiePanelLayout);
        setTiePanelLayout.setHorizontalGroup(
            setTiePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setTiePanelLayout.createSequentialGroup()
                .addGroup(setTiePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(setTiePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(setTiePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(setTiePanelLayout.createSequentialGroup()
                                .addComponent(quantityLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jRadioButton1)
                            .addComponent(isInfRadioButton)))
                    .addGroup(setTiePanelLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(setTiePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(quantityLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(infParamNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        setTiePanelLayout.setVerticalGroup(
            setTiePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(setTiePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(setTiePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityLabel)
                    .addComponent(quantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRadioButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(isInfRadioButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(setTiePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quantityLabel1)
                    .addComponent(infParamNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        okButton.setText("OK");
        okButton.addActionListener(this::okButtonActionPerformed);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(this::cancelButtonActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(setTiePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(cancelButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(setTiePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        chosenTie = null;        // TODO add your handling code here:
        this.setVisible(false);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
       try {
           setQuantity();
           setIsInf();
           chosenTie = null;
           this.setVisible(false);
           panel.repaint();
       } catch (NumberFormatException ignored) {

       }
    }//GEN-LAST:event_okButtonActionPerformed

    private void infParamNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_infParamNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_infParamNameFieldActionPerformed

    private void setQuantity() { // modified by Katya 08.12.2016
        String quantityValueStr = quantityTextField.getText();
        if (SafeParsingUtils.tryParseInt(quantityValueStr)) {
            chosenTie.setQuantity(Integer.parseInt(quantityValueStr));
            if (chosenTie.getClass() == GraphArcIn.class) {
                GraphArcIn chosenArc = (GraphArcIn) chosenTie;
                ArcIn arcIn = chosenArc.getArcIn();
                arcIn.setKParam(null);
            } else {
                GraphArcOut chosenArc = (GraphArcOut) chosenTie;
                ArcOut arcOut = chosenArc.getArcOut();
                arcOut.setKParam(null);
            }
        } else {
            if (chosenTie.getClass() == GraphArcIn.class) {
                GraphArcIn chosenArc = (GraphArcIn) chosenTie;
                ArcIn arcIn = chosenArc.getArcIn();
                arcIn.setKParam(quantityValueStr);
            } else {
                GraphArcOut chosenArc = (GraphArcOut) chosenTie;
                ArcOut arcOut = chosenArc.getArcOut();
                arcOut.setKParam(quantityValueStr);
            }
        }
    }

    private void getQuantity() { // modified by Katya 08.12.2016
        String quantityStr;
        if (chosenTie.getClass() == GraphArcIn.class) {
            GraphArcIn chosenArc = (GraphArcIn) chosenTie;
            ArcIn arcIn = chosenArc.getArcIn();
            quantityStr = arcIn.kIsParam()
                ? arcIn.getKParamName()
                : Integer.toString(chosenTie.getQuantity());
        } else {
            GraphArcOut chosenArc = (GraphArcOut) chosenTie;
            ArcOut arcOut = chosenArc.getArcOut();
            quantityStr = arcOut.kIsParam()
                ? arcOut.getKParamName()
                : Integer.toString(chosenTie.getQuantity());
        }
        quantityTextField.setText(quantityStr);
    }

    private void setIsInf() { // modified by Katya 08.12.2016
        if (chosenTie.getClass() == GraphArcIn.class) {
            boolean isInfValue = isInfRadioButton.isSelected();
            String isInfParamName = infParamNameField.getText();
            GraphArcIn chosenArc = (GraphArcIn) chosenTie;
            ArcIn arcIn = chosenArc.getArcIn();
            if (isInfParamName != null && !isInfParamName.isEmpty()) {
                arcIn.setInfParam(isInfParamName);
            } else {
                arcIn.setInf(isInfValue);
                arcIn.setInfParam(null);
            }
        } else {
            chosenTie.setInf(false);
        }
    }

    private void getIsInf() { // modified by Katya 08.12.2016
        if (chosenTie.getClass() == GraphArcIn.class) {
            GraphArcIn chosenArc = (GraphArcIn) chosenTie;
            ArcIn arcIn = chosenArc.getArcIn();
            isInfRadioButton.setSelected(chosenTie.getIsInf());
            infParamNameField.setText(arcIn.getInfParamName());
        } else {
            isInfRadioButton.setSelected(false);
            infParamNameField.setText(null);
        }
    }

    private void setChosenTie(GraphArc t) {
        chosenTie = t;
    }

    public void setInfo(GraphArc t) {
        setChosenTie(t);
        getQuantity();
        getIsInf();
    }
}
